name: Haskell CI

env:
  VERSION: "0.1.0.0"
  CACHIX_REPO: paolino
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: ${{ env.CACHIX_REPO }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run tests
      run: |
        nix build .#github-on-cardano-tests
        ./result/bin/github-on-cardano-tests
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: ${{ env.CACHIX_REPO }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: |
        nix build .#github-on-cardano

  bundles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: ${{ env.CACHIX_REPO }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Bundle github-on-cardano
      run: |
        nix bundle .#github-on-cardano
        cp -L github-on-cardano-exe-github-on-cardano-arx github-on-cardano
        rm github-on-cardano-exe-github-on-cardano-arx
    - name: Archive github-on-cardano
      uses: actions/upload-artifact@v4
      with:
        name: github-on-cardano
        path: |
          ./github-on-cardano
    - name: Bundle github-on-cardano docker-image
      run: |
            nix bundle --bundler github:NixOS/bundlers#toDockerImage .#github-on-cardano
            cp -L ./github-on-cardano-exe-github-on-cardano-${{ env.VERSION }}.tar.gz \
              ./github-on-cardano-docker-image.tar.gz
            rm ./github-on-cardano-exe-github-on-cardano-${{ env.VERSION }}.tar.gz
    - name: Archive github-on-cardano docker-image
      uses: actions/upload-artifact@v4
      with:
        name: github-on-cardano-docker-image
        path: |
          ./github-on-cardano-docker-image.tar.gz
