name: Haskell CI

env:
  VERSION: "0.1.0.0"
  CACHIX_REPO: paolino
  REPO: github-on-cardano
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: $CACHIX_REPO
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run tests
      run: |
        cd haskell
        nix build .#${{repo}}-tests
        ./result/bin/${{repo}}-tests
  builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: $CACHIX_REPO
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build ${{repo}}
      run: |
        cd haskell
        nix build .#${{repo}}

  bundles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: $CACHIX_REPO
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Bundle ${{repo}}
      run: |
        cd haskell
        nix bundle .#${{repo}}
        cp -L logins-exe-${{repo}}-arx ${{repo}}
        rm logins-exe-${{repo}}-arx
    - name: Archive ${{repo}}
      uses: actions/upload-artifact@v4
      with:
        name: ${{repo}}
        path: |
          haskell/${{repo}}